# Generated by Django 3.2.5 on 2021-09-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210825_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='sanjeev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_1', models.TextField(max_length=30, null=True)),
                ('caption_2', models.TextField(max_length=30, null=True)),
                ('caption_3', models.TextField(max_length=30, null=True)),
                ('caption_4', models.TextField(max_length=30, null=True)),
                ('caption_5', models.TextField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='caption_1',
        ),
        migrations.RemoveField(
            model_name='image',
            name='caption_2',
        ),
        migrations.RemoveField(
            model_name='image',
            name='caption_3',
        ),
        migrations.RemoveField(
            model_name='image',
            name='caption_4',
        ),
        migrations.RemoveField(
            model_name='image',
            name='caption_5',
        ),
    ]
