# Generated by Django 3.2.5 on 2021-09-01 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210901_1051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sanjeev',
            new_name='caption',
        ),
    ]
