# Generated by Django 3.2.5 on 2021-09-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210901_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='caption_1',
        ),
        migrations.RemoveField(
            model_name='image',
            name='caption_2',
        ),
        migrations.RemoveField(
            model_name='image',
            name='caption_3',
        ),
        migrations.RemoveField(
            model_name='image',
            name='caption_4',
        ),
        migrations.RemoveField(
            model_name='image',
            name='caption_5',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(default=1, max_length=255, upload_to=''),
            preserve_default=False,
        ),
    ]
